<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class FlexDuct
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class FlexDuct
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_FlexDuct.md&amp;value=---%0Auid%3A%20OpenMEP.Element.FlexDuct%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.FlexDuct">


  <h1 id="OpenMEP_Element_FlexDuct" data-uid="OpenMEP.Element.FlexDuct" class="text-break">
    Class FlexDuct
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/FlexDuct.cs/#L12"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>A flex duct in the Autodesk Revit MEP product.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class FlexDuct</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">FlexDuct</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>





  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_FlexDuct_CreateByConnectorAndPoints_" data-uid="OpenMEP.Element.FlexDuct.CreateByConnectorAndPoints*"></a>

  <h3 id="OpenMEP_Element_FlexDuct_CreateByConnectorAndPoints_Autodesk_Revit_DB_Connector_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__Revit_Elements_Element_" data-uid="OpenMEP.Element.FlexDuct.CreateByConnectorAndPoints(Autodesk.Revit.DB.Connector,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point},Revit.Elements.Element)">
  CreateByConnectorAndPoints(Connector, List&lt;Point&gt;, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/FlexDuct.cs/#L104"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Adds a new flexible duct into the document,
using a connector, point array and duct type.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByConnectorAndPoints(Connector connector, List&lt;Point&gt; points, Element ductType)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector</code> <span class="xref">Connector</span></dt>
    <dd><p>The connector to be connected to the duct, including the end points.</p>
</dd>
    <dt><code>points</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point</span>&gt;</dt>
    <dd><p>The point array indicating the path of the flexible duct.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The type of the flexible duct.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then a new flexible duct is returned,
otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_FlexDuct_CreateByConnectorAndPoints_Autodesk_Revit_DB_Connector_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/FlexDuct.NewFlexDuctByConnectorAndPoints.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_FlexDuct_CreateByConnectorAndPoints_Autodesk_Revit_DB_Connector_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the connector is a fitting or equipment connector of the correct domain,
and if the connector's direction matches the direction of the flexible duct to be created,
the connectors will be automatically connected. A transition fitting will be added
at the connector(s) if necessary. If the connector's type, domain,
does not match the one of the input connector, no connection will be established.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>Thrown when the input argument connector or points is <span class="xref">null</span>.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the flexible duct cannot be created or regenerate fails.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>Thrown if the flexible duct type does not exist in the given document.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_FlexDuct_CreateByListPoint_" data-uid="OpenMEP.Element.FlexDuct.CreateByListPoint*"></a>

  <h3 id="OpenMEP_Element_FlexDuct_CreateByListPoint_Revit_Elements_Element_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__" data-uid="OpenMEP.Element.FlexDuct.CreateByListPoint(Revit.Elements.Element,System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point})">
  CreateByListPoint(Element, List&lt;Point&gt;)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/FlexDuct.cs/#L69"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Adds a new flexible duct into the document,
using a point array and duct type.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByListPoint(Element ductType, List&lt;Point&gt; points)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The type of the flexible duct.</p>
</dd>
    <dt><code>points</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point</span>&gt;</dt>
    <dd><p>The point array indicating the path of the flexible duct, including the end points.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then a new flexible duct is returned,
otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_FlexDuct_CreateByListPoint_Revit_Elements_Element_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point___examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/FlexDuct.NewFlexDuctByListPoint.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>Thrown when the input argument points is <span class="xref">null</span>.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the flexible duct cannot be created or regenerate fails.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>Thrown if the flexible duct type does not exist in the given document.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_FlexDuct_CreateByTwoConnector_" data-uid="OpenMEP.Element.FlexDuct.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_FlexDuct_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.FlexDuct.CreateByTwoConnector(Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  CreateByTwoConnector(Element, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/FlexDuct.cs/#L40"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Adds a new flexible duct into the document,
using two connector, and duct type.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element ductType, Connector connector1, Connector connector2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The type of the flexible duct.</p>
</dd>
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the duct.</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the duct.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then a new flexible duct is returned,
otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_FlexDuct_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/FlexDuct.NewFlexDuctByTwoConnector.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_FlexDuct_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the connectors are fitting or equipment connectors of the correct domain,
and if the connectors' direction match the direction of the flexible duct to be created,
the connectors will be automatically connected. A transition fitting will be added
at the connector(s) if necessary. If the connector's type, domain,
does not match the one of the input connector, no connection will be established.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>Thrown when the input argument connector1 or connector2 is <span class="xref">null</span>.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the flexible duct cannot be created or regenerate fails.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>Thrown if the flexible duct type does not exist in the given document.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_FlexDuct_Points_" data-uid="OpenMEP.Element.FlexDuct.Points*"></a>

  <h3 id="OpenMEP_Element_FlexDuct_Points_Revit_Elements_Element_" data-uid="OpenMEP.Element.FlexDuct.Points(Revit.Elements.Element)">
  Points(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/FlexDuct.cs/#L126"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The points of the flex duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static IEnumerable&lt;Point&gt; Points(Element flexDuct)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>flexDuct</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Point</span>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_FlexDuct_Points_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/FlexDuct.Points.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_FlexDuct_Points_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the points of flex duct, including the end points.
If the end points are changed, the connection will be maintained by Revit automatically.
The set operation will fail if the modification makes the connection invalid.</p>
<p>flex Duct</p>
</div>




</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_FlexDuct.md&amp;value=---%0Auid%3A%20OpenMEP.Element.FlexDuct%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>