<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Conduit
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Conduit
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Conduit.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Conduit%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.Conduit">


  <h1 id="OpenMEP_Element_Conduit" data-uid="OpenMEP.Element.Conduit" class="text-break">
    Class Conduit
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L9"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>This class represents a conduit in Autodesk Revit.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class Conduit</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Conduit</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>





  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_Conduit_CreateByLine_" data-uid="OpenMEP.Element.Conduit.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByLine_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Conduit.CreateByLine(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,Revit.Elements.Element,System.Double)">
  CreateByLine(Element, Line, Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L286"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Create a conduit by line</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element conduitType, Line line, Element level, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line define to draw conduit from start point to end point</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>the element of level</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>the value diameter of conduit</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new conduit</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByLine_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByLineDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Conduit_CreateByLine_" data-uid="OpenMEP.Element.Conduit.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByLine_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_Revit_Elements_Element_" data-uid="OpenMEP.Element.Conduit.CreateByLine(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,Revit.Elements.Element)">
  CreateByLine(Element, Line, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L258"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Create a conduit by line</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element conduitType, Line line, Element level)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line define to draw conduit from start point to end point</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>the element of level</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new conduit</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByLine_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByLine.png" alt=""></p>






  <a id="OpenMEP_Element_Conduit_CreateByTwoConnector_" data-uid="OpenMEP.Element.Conduit.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Conduit.CreateByTwoConnector(Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Revit.Elements.Element,System.Double)">
  CreateByTwoConnector(Element, Connector, Connector, Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L236"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new instance of conduit.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element conduitType, Connector firstConnector, Connector secondConnector, Element level, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>firstConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to get start point</p>
</dd>
    <dt><code>secondConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to get endpoint</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the level which this conduit based.
If the input level id is invalidElementId = -1, the nearest level will be used.</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>the value diameter of conduit</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The newly created conduit.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByTwoConnectorDiameter.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This method will regenerate the document.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>This conduit type is invalid.
-or-
This level id is invalid.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationForbiddenException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).
-or-
The document is being loaded, or is in the midst of another
sensitive process.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationOutsideTransactionException</span></dt>
    <dd><p>The document has no open transaction.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Conduit_CreateByTwoConnector_" data-uid="OpenMEP.Element.Conduit.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element_" data-uid="OpenMEP.Element.Conduit.CreateByTwoConnector(Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Revit.Elements.Element)">
  CreateByTwoConnector(Element, Connector, Connector, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L175"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new instance of conduit.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element conduitType, Connector firstConnector, Connector secondConnector, Element level)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>firstConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to get start point</p>
</dd>
    <dt><code>secondConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to get endpoint</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the level which this conduit based.
If the input level id is invalidElementId = -1, the nearest level will be used.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The newly created conduit.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByTwoConnector.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoConnector_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This method will regenerate the document.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>This conduit type is invalid.
-or-
This level id is invalid.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationForbiddenException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).
-or-
The document is being loaded, or is in the midst of another
sensitive process.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationOutsideTransactionException</span></dt>
    <dd><p>The document has no open transaction.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Conduit_CreateByTwoPoint_" data-uid="OpenMEP.Element.Conduit.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Conduit.CreateByTwoPoint(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Revit.Elements.Element,System.Double)">
  CreateByTwoPoint(Element, Point, Point, Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L121"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new instance of conduit.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element conduitType, Point startPoint, Point endPoint, Element level, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the conduit location line.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the conduit location line.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the level which this conduit based.
If the input level id is invalidElementId = -1, the nearest level will be used.</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>diameter value of conduit</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The newly created conduit.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByTwoPointDiameter.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This method will regenerate the document.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>This conduit type is invalid.
-or-
This level id is invalid.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationForbiddenException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).
-or-
The document is being loaded, or is in the midst of another
sensitive process.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationOutsideTransactionException</span></dt>
    <dd><p>The document has no open transaction.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Conduit_CreateByTwoPoint_" data-uid="OpenMEP.Element.Conduit.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element_" data-uid="OpenMEP.Element.Conduit.CreateByTwoPoint(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Revit.Elements.Element)">
  CreateByTwoPoint(Element, Point, Point, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L60"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new instance of conduit.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element conduitType, Point startPoint, Point endPoint, Element level)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduitType</code> <span class="xref">Element</span></dt>
    <dd><p>The conduit type.  This must be a conduit type accepted by isValidConduitType().
If the input conduit type is InvalidElementId, the default conduit type from the document will be used.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the conduit location line.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the conduit location line.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the level which this conduit based.
If the input level id is invalidElementId = -1, the nearest level will be used.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The newly created conduit.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.CreateByTwoPoint.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Conduit_CreateByTwoPoint_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This method will regenerate the document.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>This conduit type is invalid.
-or-
This level id is invalid.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationForbiddenException</span></dt>
    <dd><p>The document is in failure mode: an operation has failed,
and Revit requires the user to either cancel the operation
or fix the problem (usually by deleting certain elements).
-or-
The document is being loaded, or is in the midst of another
sensitive process.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ModificationOutsideTransactionException</span></dt>
    <dd><p>The document has no open transaction.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Conduit_SetDiameter_" data-uid="OpenMEP.Element.Conduit.SetDiameter*"></a>

  <h3 id="OpenMEP_Element_Conduit_SetDiameter_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Conduit.SetDiameter(Revit.Elements.Element,System.Double)">
  SetDiameter(Element?, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Conduit.cs/#L304"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set diameter of conduit</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? SetDiameter(Element? conduit, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>conduit</code> <span class="xref">Element</span></dt>
    <dd><p>conduit need to set</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>diameter to set</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>conduit</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Conduit_SetDiameter_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Conduit.SetDiameter.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.exception">Exception</a></dt>
    <dd></dd>
  </dl>



</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Conduit.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Conduit%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>