<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Pipe
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Pipe
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Pipe.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Pipe%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.Pipe">


  <h1 id="OpenMEP_Element_Pipe" data-uid="OpenMEP.Element.Pipe" class="text-break">
    Class Pipe
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L15"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>A pipe in the Autodesk Revit MEP product.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class Pipe</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Pipe</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>




  <h2 id="OpenMEP_Element_Pipe_remarks">Remarks</h2>
  <div class="markdown level0 remarks"><p>The pipe is only available in the Autodesk Revit MEP product.</p>
</div>

  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_" data-uid="OpenMEP.Element.Pipe.CreateByConnectorAndPoint*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_System_Double_" data-uid="OpenMEP.Element.Pipe.CreateByConnectorAndPoint(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.DesignScript.Geometry.Point,System.Double)">
  CreateByConnectorAndPoint(Element, Element, Connector, Point, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L106"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with start connector and end point</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByConnectorAndPoint(Element pipeType, Element level, Connector connector1, Point endPoint, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>the element type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>the element level</p>
</dd>
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>first connector to define first pipe draw pipe</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>end point to draw pipe</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>size of new pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByConnectorAndPointDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_" data-uid="OpenMEP.Element.Pipe.CreateByConnectorAndPoint*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Pipe.CreateByConnectorAndPoint(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.DesignScript.Geometry.Point)">
  CreateByConnectorAndPoint(Element, Element, Connector, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L79"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with start connector and end point</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByConnectorAndPoint(Element pipeType, Element level, Connector connector1, Point endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>the element type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>the element level</p>
</dd>
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>first connector to define first pipe draw pipe</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>end point to draw pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByConnectorAndPoint.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByLine_" data-uid="OpenMEP.Element.Pipe.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double_" data-uid="OpenMEP.Element.Pipe.CreateByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,System.Double)">
  CreateByLine(Element, Element, Element, Line, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L230"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Create a new pipe by line</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element systemType, Element pipeType, Element level, Line line, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>the element of pipe system type</p>
</dd>
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>the element type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>element level</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>line to draw pipe</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>size of new pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByLineDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByLine_" data-uid="OpenMEP.Element.Pipe.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_" data-uid="OpenMEP.Element.Pipe.CreateByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line)">
  CreateByLine(Element, Element, Element, Line)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L204"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Create a new pipe by line</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element systemType, Element pipeType, Element level, Line line)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>the element of pipe system type</p>
</dd>
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>the element type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>element level</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>line to draw pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByLine.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByPointAndDirection_" data-uid="OpenMEP.Element.Pipe.CreateByPointAndDirection*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByPointAndDirection_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Vector_System_Double_System_Double_" data-uid="OpenMEP.Element.Pipe.CreateByPointAndDirection(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,System.Double,System.Double)">
  CreateByPointAndDirection(Element, Element, Element, Point, Vector, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L181"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe by direction and length</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByPointAndDirection(Element systemType, Element pipeType, Element level, Point startPoint, Vector direction, double length, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the piping system type.</p>
</dd>
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the pipe type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The Element level.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the pipe.</p>
</dd>
    <dt><code>direction</code> <span class="xref">Vector</span></dt>
    <dd><p>direction of new pipe</p>
</dd>
    <dt><code>length</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd></dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>size of new pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByPointAndDirection_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Vector_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByPointAndDirection.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByTwoConnector_" data-uid="OpenMEP.Element.Pipe.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_System_Double_" data-uid="OpenMEP.Element.Pipe.CreateByTwoConnector(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,System.Double)">
  CreateByTwoConnector(Element, Element, Connector, Connector, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L58"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with connectors</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element pipeType, Element level, Connector connector1, Connector connector2, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>level</p>
</dd>
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>first connector</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>second connector</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>size of pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByTwoConnectorDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByTwoConnector_" data-uid="OpenMEP.Element.Pipe.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Pipe.CreateByTwoConnector(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  CreateByTwoConnector(Element, Element, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L32"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with connectors</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element pipeType, Element level, Connector connector1, Connector connector2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>type of pipe</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>level</p>
</dd>
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>first connector</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>second connector</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByTwoConnector.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByTwoPoint_" data-uid="OpenMEP.Element.Pipe.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double_" data-uid="OpenMEP.Element.Pipe.CreateByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,System.Double)">
  CreateByTwoPoint(Element, Element, Element, Point, Point, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L156"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with two points</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element systemType, Element pipeType, Element level, Point startPoint, Point endPoint, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the piping system type.</p>
</dd>
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the pipe type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The Element level.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the pipe.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the pipe.</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>size of new pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByTwoPointDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_CreateByTwoPoint_" data-uid="OpenMEP.Element.Pipe.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Pipe_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Pipe.CreateByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
  CreateByTwoPoint(Element, Element, Element, Point, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L128"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create new pipe with two points</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element systemType, Element pipeType, Element level, Point startPoint, Point endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the piping system type.</p>
</dd>
    <dt><code>pipeType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the pipe type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The Element level.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the pipe.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the pipe.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.CreateByTwoPoint.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_EndCap_" data-uid="OpenMEP.Element.Pipe.EndCap*"></a>

  <h3 id="OpenMEP_Element_Pipe_EndCap_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.EndCap(Revit.Elements.Element)">
  EndCap(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L797"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Places caps on the open connectors of the pipe curve, pipe fitting or pipe accessory.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void EndCap(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>Element of pipe curve, pipe fitting or pipe accessory.</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Pipe_EndCap_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.EndCap.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_EndCap_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>In order to place the cap, the cap type should be defined in the routing preferences that associates with the pipe type of the given element.
If the typeId is a valid element id, it will be used to override the pipe type that associates with the pipe type of the given element.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The element elemId does not exist in the document
-or-
The element elemId is neither an object of pipe curve, pipe fitting, nor pipe accessory.
-or-
The element elemId has no opened piping connector.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>this operation failed.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Pipe_GetCross_" data-uid="OpenMEP.Element.Pipe.GetCross*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetCross_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetCross(Revit.Elements.Element)">
  GetCross(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L652"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return Cross Of Pipe In Routing Preferences</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? GetCross(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>cross</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetCross_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetCross.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetDiameter_" data-uid="OpenMEP.Element.Pipe.GetDiameter*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetDiameter_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetDiameter(Revit.Elements.Element)">
  GetDiameter(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L301"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return information diameter of pipe</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;OverallSize&quot;, &quot;Diameter&quot;, &quot;OutsideDiameter&quot;, &quot;InsideDiameter&quot; })]
public static Dictionary&lt;string, object?&gt; GetDiameter(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2">Dictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetDiameter_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetFamilySymbolCapsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolCapsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolCapsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolCapsByRouting(Revit.Elements.Element)">
  GetFamilySymbolCapsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L368"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Caps family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolCapsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolCapsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolCapsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolCapsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolCrossesByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolCrossesByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolCrossesByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolCrossesByRouting(Revit.Elements.Element)">
  GetFamilySymbolCrossesByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L398"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Crosses family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolCrossesByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolCrossesByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolCrossesByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolCrossesByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolElbowsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolElbowsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolElbowsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolElbowsByRouting(Revit.Elements.Element)">
  GetFamilySymbolElbowsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L428"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Elbows family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolElbowsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolElbowsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolElbowsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolElbowsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolJunctionsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolJunctionsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolJunctionsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolJunctionsByRouting(Revit.Elements.Element)">
  GetFamilySymbolJunctionsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L338"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Junctions family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolJunctionsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolJunctionsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolJunctionsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolJunctionsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolMechanicalJointsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolMechanicalJointsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolMechanicalJointsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolMechanicalJointsByRouting(Revit.Elements.Element)">
  GetFamilySymbolMechanicalJointsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L548"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return MechanicalJoints family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static Dictionary&lt;string, object?&gt; GetFamilySymbolMechanicalJointsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2">Dictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolMechanicalJointsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolMechanicalJointsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolMechanicalJointsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolSegmentsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolSegmentsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolSegmentsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolSegmentsByRouting(Revit.Elements.Element)">
  GetFamilySymbolSegmentsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L488"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Segments family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolSegmentsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolSegmentsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolSegmentsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolSegmentsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolTransitionsByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolTransitionsByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolTransitionsByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolTransitionsByRouting(Revit.Elements.Element)">
  GetFamilySymbolTransitionsByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L458"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Transitions family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolTransitionsByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolTransitionsByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolTransitionsByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolTransitionsByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetFamilySymbolUndefinedByRouting_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolUndefinedByRouting*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetFamilySymbolUndefinedByRouting_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetFamilySymbolUndefinedByRouting(Revit.Elements.Element)">
  GetFamilySymbolUndefinedByRouting(Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L518"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return Undefined family of pipe get in routing setting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;FamilySymbol&quot;, &quot;Family&quot; })]
public static IDictionary? GetFamilySymbolUndefinedByRouting(Element? pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get family routing</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd><p>family symbol</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolUndefinedByRouting_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetFamilySymbolUndefinedByRouting.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_GetFamilySymbolUndefinedByRouting_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>it will be help you get correct family junction in setting map with size of pipe</p>
</div>




  <a id="OpenMEP_Element_Pipe_GetRoughness_" data-uid="OpenMEP.Element.Pipe.GetRoughness*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetRoughness_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetRoughness(Revit.Elements.Element)">
  GetRoughness(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L701"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return The roughness of the MEP curve type</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static double GetRoughness(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>roughness</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetRoughness_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetRoughness.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetTap_" data-uid="OpenMEP.Element.Pipe.GetTap*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetTap_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetTap(Revit.Elements.Element)">
  GetTap(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L668"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return Tap Of Pipe In Routing Preferences</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? GetTap(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>tap</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetTap_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetTap.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetTee_" data-uid="OpenMEP.Element.Pipe.GetTee*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetTee_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetTee(Revit.Elements.Element)">
  GetTee(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L620"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return Tee Of Pipe In Routing Preferences</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? GetTee(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>tee</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetTee_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetTee.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetTransition_" data-uid="OpenMEP.Element.Pipe.GetTransition*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetTransition_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetTransition(Revit.Elements.Element)">
  GetTransition(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L685"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return Transition Of Pipe In Routing Preferences</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? GetTransition(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>transition</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetTransition_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetTransition.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_GetUnion_" data-uid="OpenMEP.Element.Pipe.GetUnion*"></a>

  <h3 id="OpenMEP_Element_Pipe_GetUnion_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.GetUnion(Revit.Elements.Element)">
  GetUnion(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L636"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return Union Of Pipe In Routing Preferences</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? GetUnion(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>union</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_GetUnion_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.GetUnion.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_MEPSystem_" data-uid="OpenMEP.Element.Pipe.MEPSystem*"></a>

  <h3 id="OpenMEP_Element_Pipe_MEPSystem_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.MEPSystem(Revit.Elements.Element)">
  MEPSystem(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L735"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The system of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static Element? MEPSystem(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>Returns the system of this MEP curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_MEPSystem_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.MEPSystem.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_MEPSystem_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the curve does not belong to any systems, the value will be <span class="xref">null</span>.
If the curve belongs to more than one system, the first available value is returned.</p>
</div>




  <a id="OpenMEP_Element_Pipe_SetDiameter_" data-uid="OpenMEP.Element.Pipe.SetDiameter*"></a>

  <h3 id="OpenMEP_Element_Pipe_SetDiameter_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Pipe.SetDiameter(Revit.Elements.Element,System.Double)">
  SetDiameter(Element?, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L274"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set diameter of pipe</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? SetDiameter(Element? pipe, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe need to set</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>diameter to set</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_SetDiameter_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.SetDiameter.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.exception">Exception</a></dt>
    <dd></dd>
  </dl>



  <a id="OpenMEP_Element_Pipe_SetSystemType_" data-uid="OpenMEP.Element.Pipe.SetSystemType*"></a>

  <h3 id="OpenMEP_Element_Pipe_SetSystemType_Revit_Elements_Element_System_Int32_" data-uid="OpenMEP.Element.Pipe.SetSystemType(Revit.Elements.Element,System.Int32)">
  SetSystemType(Element, int)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L762"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Updates the associated system type for the pipe.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element SetSystemType(Element pipe, int systemTypeId)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to set system type</p>
</dd>
    <dt><code>systemTypeId</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.int32">int</a></dt>
    <dd><p>The ElementId of the piping system type.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_SetSystemType_Revit_Elements_Element_System_Int32__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.SetSystemType.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Pipe_SetSystemType_Revit_Elements_Element_System_Int32__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the pipe previously did not have a system associated to it, this will create a new system.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemTypeId is not valid piping system type.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Pipe_Shape_" data-uid="OpenMEP.Element.Pipe.Shape*"></a>

  <h3 id="OpenMEP_Element_Pipe_Shape_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.Shape(Revit.Elements.Element)">
  Shape(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L716"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return The shape of the profile.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static dynamic? Shape(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get shape</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">dynamic</span></dt>
    <dd><p>connectorProfileType</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_Shape_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.Shape.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_Split_" data-uid="OpenMEP.Element.Pipe.Split*"></a>

  <h3 id="OpenMEP_Element_Pipe_Split_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Pipe.Split(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
  Split(Element, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L249"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>split a pipe at a point</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[Obsolete(&quot;This node is deprecated, please use the new node named &#39;MepCurve.BreakCurve&#39; instead.&quot;)]
public static Element? Split(Element pipe, Point point)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe will be break</p>
</dd>
    <dt><code>point</code> <span class="xref">Point</span></dt>
    <dd><p>point on pipe to break</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new pipe has split</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_Split_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.Split.png" alt=""></p>






  <a id="OpenMEP_Element_Pipe_SystemType_" data-uid="OpenMEP.Element.Pipe.SystemType*"></a>

  <h3 id="OpenMEP_Element_Pipe_SystemType_Revit_Elements_Element_" data-uid="OpenMEP.Element.Pipe.SystemType(Revit.Elements.Element)">
  SystemType(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Pipe.cs/#L601"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return system type of pipe</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static Element? SystemType(Element pipe)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>pipe</code> <span class="xref">Element</span></dt>
    <dd><p>pipe to get</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>system type of pipe</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Pipe_SystemType_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Pipe.SystemType.png" alt=""></p>






</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Pipe.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Pipe%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>