<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Fitting
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Fitting
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Fitting.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Fitting%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.Fitting">


  <h1 id="OpenMEP_Element_Fitting" data-uid="OpenMEP.Element.Fitting" class="text-break">
    Class Fitting
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L21"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>This object represents a single instance of a family type, such as a single I beam.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class Fitting</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Fitting</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>




  <h2 id="OpenMEP_Element_Fitting_remarks">Remarks</h2>
  <div class="markdown level0 remarks"><p>Examples of FamilyInstance objects within Autodesk Revit are Beams, Columns,
Braces and Desks. The FamilyInstance object provides more detailed properties that
enable the type of the family instance to be changed, thus changing their appearance
within the project.</p>
</div>

  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_Fitting_ConnectorInfo_" data-uid="OpenMEP.Element.Fitting.ConnectorInfo*"></a>

  <h3 id="OpenMEP_Element_Fitting_ConnectorInfo_Revit_Elements_Element_" data-uid="OpenMEP.Element.Fitting.ConnectorInfo(Revit.Elements.Element)">
  ConnectorInfo(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L272"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return information connector of fitting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;Size&quot;, &quot;PartType&quot; })]
[NodeCategory(&quot;Query&quot;)]
public static IDictionary ConnectorInfo(Element fitting)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>fitting</code> <span class="xref">Element</span></dt>
    <dd><p>family instance</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.idictionary">IDictionary</a></dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_ConnectorInfo_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.ConnectorInfo.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewCrossFitting_" data-uid="OpenMEP.Element.Fitting.NewCrossFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewCrossFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Fitting.NewCrossFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  NewCrossFitting(Connector, Connector, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L97"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of a cross fitting into the Autodesk Revit document, using four connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewCrossFitting(Connector connector1, Connector connector2, Connector connector3, Connector connector4)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the cross.</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the cross.</p>
</dd>
    <dt><code>connector3</code> <span class="xref">Connector</span></dt>
    <dd><p>The third connector to be connected to the cross.</p>
</dd>
    <dt><code>connector4</code> <span class="xref">Connector</span></dt>
    <dd><p>The fourth connector to be connected to the cross</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then an family instance to the new object is returned, and the transition fitting will be added at the connectors' end if necessary, otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewCrossFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewCrossFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewElbowFitting_" data-uid="OpenMEP.Element.Fitting.NewElbowFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewElbowFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Fitting.NewElbowFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  NewElbowFitting(Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L74"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an elbow fitting into the Autodesk Revit document, using two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewElbowFitting(Connector firstConnector, Connector secondConnector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>firstConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the union.</p>
</dd>
    <dt><code>secondConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the union.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then an family instance to the new object is returned, otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewElbowFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewElbowFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewTakeoffFitting_" data-uid="OpenMEP.Element.Fitting.NewTakeoffFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewTakeoffFitting_Autodesk_Revit_DB_Connector_Revit_Elements_Element_" data-uid="OpenMEP.Element.Fitting.NewTakeoffFitting(Autodesk.Revit.DB.Connector,Revit.Elements.Element)">
  NewTakeoffFitting(Connector, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L183"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an takeoff fitting into the Autodesk Revit document, using one connector and one MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTakeoffFitting(Connector connector, Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector</code> <span class="xref">Connector</span></dt>
    <dd><p>The connector to be connected to the takeoff.</p>
</dd>
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd><p>The duct or pipe which is the trunk for the takeoff.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new takeoff</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewTakeoffFitting_Autodesk_Revit_DB_Connector_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewTakeoffFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewTeeFitting_" data-uid="OpenMEP.Element.Fitting.NewTeeFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewTeeFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Fitting.NewTeeFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  NewTeeFitting(Connector, Connector?, Connector?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L139"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of a tee fitting into the Autodesk Revit document, using three connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTeeFitting(Connector connector1, Connector? connector2, Connector? connector3)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the tee</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the tee.</p>
</dd>
    <dt><code>connector3</code> <span class="xref">Connector</span></dt>
    <dd><p>The third connector to be connected to the tee. This should be connected to the branch of the tee.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then an family instance to the new object is returned, and the transition fitting will be added at the connectors' end if necessary, otherwise an exception with failure information will be thrown</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewTeeFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewTeeFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewTransitionFitting_" data-uid="OpenMEP.Element.Fitting.NewTransitionFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewTransitionFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Fitting.NewTransitionFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  NewTransitionFitting(Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L205"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an transition fitting into the Autodesk Revit document, using two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTransitionFitting(Connector connector1, Connector connector2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector1</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the transition.</p>
</dd>
    <dt><code>connector2</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the transition.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new transition</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewTransitionFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewTransitionFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_NewUnionFitting_" data-uid="OpenMEP.Element.Fitting.NewUnionFitting*"></a>

  <h3 id="OpenMEP_Element_Fitting_NewUnionFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Fitting.NewUnionFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  NewUnionFitting(Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L36"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an union fitting into the Autodesk Revit document, using two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewUnionFitting(Connector firstConnector, Connector secondConnector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>firstConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector to be connected to the union.</p>
</dd>
    <dt><code>secondConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second connector to be connected to the union.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>If creation was successful then an family instance to the new object is returned, otherwise an exception with failure information will be thrown.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_NewUnionFitting_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.NewUnionFitting.png" alt=""></p>






  <a id="OpenMEP_Element_Fitting_SetAngle_" data-uid="OpenMEP.Element.Fitting.SetAngle*"></a>

  <h3 id="OpenMEP_Element_Fitting_SetAngle_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Fitting.SetAngle(Revit.Elements.Element,System.Double)">
  SetAngle(Element?, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L227"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set Angle of tee fitting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Action&quot;)]
public static Element? SetAngle(Element? fitting, double angle)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>fitting</code> <span class="xref">Element</span></dt>
    <dd><p>fitting need to change angle</p>
</dd>
    <dt><code>angle</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>angle to set (degrees)</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_SetAngle_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.SetAngle.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Fitting_SetAngle_Revit_Elements_Element_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>this function just apply for tee have two connector</p>
</div>




  <a id="OpenMEP_Element_Fitting_SetRadius_" data-uid="OpenMEP.Element.Fitting.SetRadius*"></a>

  <h3 id="OpenMEP_Element_Fitting_SetRadius_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Fitting.SetRadius(Revit.Elements.Element,System.Double)">
  SetRadius(Element?, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Fitting.cs/#L249"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set radius of fitting</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Action&quot;)]
public static Element? SetRadius(Element? fitting, double radius)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>fitting</code> <span class="xref">Element</span></dt>
    <dd><p>fitting will be set</p>
</dd>
    <dt><code>radius</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>value radius</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Fitting_SetRadius_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Fitting.SetRadius.png" alt=""></p>






</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Fitting.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Fitting%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>