<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class MEPCurve
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class MEPCurve
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_MEPCurve.md&amp;value=---%0Auid%3A%20OpenMEP.Element.MEPCurve%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.MEPCurve">


  <h1 id="OpenMEP_Element_MEPCurve" data-uid="OpenMEP.Element.MEPCurve" class="text-break">
    Class MEPCurve
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L19"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>A class can use for DuctType, PipeType, CableTrayType, ConduitType, WireType, MEPCurveType</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class MEPCurve</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">MEPCurve</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>





  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_MEPCurve_BreakCurve_" data-uid="OpenMEP.Element.MEPCurve.BreakCurve*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_BreakCurve_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.MEPCurve.BreakCurve(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
  BreakCurve(Element, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L34"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>break mep curve at point</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Action&quot;)]
[NodeSearchTags(new string[] { &quot;split&quot;, &quot;cut&quot;, &quot;divide&quot; })]
public static Element? BreakCurve(Element mepCurve, Point point)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend elements.</p>
</dd>
    <dt><code>point</code> <span class="xref">Point</span></dt>
    <dd><p>location to break on mep curve</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new element break from mep curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_BreakCurve_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.BreakCurve.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_Diameter_" data-uid="OpenMEP.Element.MEPCurve.Diameter*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_Diameter_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.Diameter(Revit.Elements.Element)">
  Diameter(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L390"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The diameter of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double? Diameter(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>?</dt>
    <dd><p>diameter of mep curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_Diameter_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.Diameter.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_MEPCurve_Diameter_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the diameter of the MEP curve.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the MEP curve's Shape is not round.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_MEPCurve_GetConnectorManager_" data-uid="OpenMEP.Element.MEPCurve.GetConnectorManager*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_GetConnectorManager_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.GetConnectorManager(Revit.Elements.Element)">
  GetConnectorManager(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L512"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The connector manager of this MEP curve</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static ConnectorManager? GetConnectorManager(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">ConnectorManager</span></dt>
    <dd><p>The connector manager of this MEP curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_GetConnectorManager_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.GetConnectorManager.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_GetFourConnectorsClosest_" data-uid="OpenMEP.Element.MEPCurve.GetFourConnectorsClosest*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_GetFourConnectorsClosest_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.GetFourConnectorsClosest(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element)">
  GetFourConnectorsClosest(Element?, Element?, Element?, Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L582"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return four connector closest inside four mep curves</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;Connector1&quot;, &quot;Connector2&quot;, &quot;Connector3&quot;, &quot;Connector4&quot; })]
public static IDictionary&lt;string, object?&gt; GetFourConnectorsClosest(Element? mepCurve1, Element? mepCurve2, Element? mepCurve3, Element? mepCurve4)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first mepCurve</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second mepCurve</p>
</dd>
    <dt><code>mepCurve3</code> <span class="xref">Element</span></dt>
    <dd><p>the three mepCurve</p>
</dd>
    <dt><code>mepCurve4</code> <span class="xref">Element</span></dt>
    <dd><p>the four mepCurve</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2">IDictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_GetFourConnectorsClosest_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.GetFourConnectorsClosest.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_GetThreeConnectorsClosest_" data-uid="OpenMEP.Element.MEPCurve.GetThreeConnectorsClosest*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_GetThreeConnectorsClosest_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.GetThreeConnectorsClosest(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element)">
  GetThreeConnectorsClosest(Element?, Element?, Element?)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L551"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return three points closest inside three mep curves</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;Connector1&quot;, &quot;Connector2&quot;, &quot;Connector3&quot; })]
public static IDictionary&lt;string, object?&gt; GetThreeConnectorsClosest(Element? mepCurve1, Element? mepCurve2, Element? mepCurve3)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first mepCurve</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second mepCurve</p>
</dd>
    <dt><code>mepCurve3</code> <span class="xref">Element</span></dt>
    <dd><p>the three mepCurve</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.idictionary-2">IDictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_GetThreeConnectorsClosest_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.GetThreeConnectorsClosest.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_GetTwoConnectorClosest_" data-uid="OpenMEP.Element.MEPCurve.GetTwoConnectorClosest*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_GetTwoConnectorClosest_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.GetTwoConnectorClosest(Revit.Elements.Element,Revit.Elements.Element)">
  GetTwoConnectorClosest(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L529"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return two connectors closet of two pipes</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;Connector1&quot;, &quot;Connector2&quot; })]
public static Dictionary&lt;string, object?&gt; GetTwoConnectorClosest(Element mepCurve1, Element mepCurve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first mepCurve</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second mepCurve</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2">Dictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_GetTwoConnectorClosest_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.GetTwoConnectorClosest.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_Height_" data-uid="OpenMEP.Element.MEPCurve.Height*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_Height_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.Height(Revit.Elements.Element)">
  Height(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L447"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The height of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double? Height(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>?</dt>
    <dd><p>The height of the MEP curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_Height_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.Height.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_MEPCurve_Height_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the height of the MEP curve.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the MEP curve's Shape is not rectangular.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_MEPCurve_LevelOffset_" data-uid="OpenMEP.Element.MEPCurve.LevelOffset*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_LevelOffset_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.LevelOffset(Revit.Elements.Element)">
  LevelOffset(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L474"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The offset of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double? LevelOffset(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>?</dt>
    <dd><p>Level offset</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_LevelOffset_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.LevelOffset.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_MEPCurve_LevelOffset_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the offset of the MEP curve.
If the curve is not in a horizontal plane, this value will be the start point's offset.</p>
</div>




  <a id="OpenMEP_Element_MEPCurve_NewCrossFitting_" data-uid="OpenMEP.Element.MEPCurve.NewCrossFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewCrossFitting_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewCrossFitting(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element)">
  NewCrossFitting(Element, Element, Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L186"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of a tee fitting into the Autodesk Revit document,
using four mep curves.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewCrossFitting(Element mepCurve1, Element mepCurve2, Element mepCurve3, Element mepCurve4)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first mepCurve(Pipe/Duct/CableTray)</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second mepCurve(Pipe/Duct/CableTray)</p>
</dd>
    <dt><code>mepCurve3</code> <span class="xref">Element</span></dt>
    <dd><p>the three mepCurve(Pipe/Duct/CableTray)</p>
</dd>
    <dt><code>mepCurve4</code> <span class="xref">Element</span></dt>
    <dd><p>the four mepCurve(Pipe/Duct/CableTray)</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new cross fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewCrossFitting_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewCrossFitting.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewElbowFitting_" data-uid="OpenMEP.Element.MEPCurve.NewElbowFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewElbowFitting_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewElbowFitting(Revit.Elements.Element,Revit.Elements.Element)">
  NewElbowFitting(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L159"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create a elbow fitting from two mep curve</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewElbowFitting(Element mepCurve1, Element mepCurve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend first elements.</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe second elements.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>elbow fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewElbowFitting_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewElbowFitting.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewTakeoffFitting_" data-uid="OpenMEP.Element.MEPCurve.NewTakeoffFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewTakeoffFitting_Autodesk_Revit_DB_Connector_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewTakeoffFitting(Autodesk.Revit.DB.Connector,Revit.Elements.Element)">
  NewTakeoffFitting(Connector, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L367"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an takeoff fitting into the Autodesk Revit document,
using one connector and one MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTakeoffFitting(Connector connector, Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>connector</code> <span class="xref">Connector</span></dt>
    <dd><p>connector to be connector</p>
</dd>
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd><p>mepCurve connect to create Takeoff</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new takeoff fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewTakeoffFitting_Autodesk_Revit_DB_Connector_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewTakeoffFitting.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewTeeFitting_" data-uid="OpenMEP.Element.MEPCurve.NewTeeFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewTeeFitting_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewTeeFitting(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element)">
  NewTeeFitting(Element, Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L233"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of a tee fitting into the Autodesk Revit document,
using three mep curves.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTeeFitting(Element mepCurve1, Element mepCurve2, Element mepCurve3)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend first elements.</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend second elements.</p>
</dd>
    <dt><code>mepCurve3</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend three elements.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new tee fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewTeeFitting_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewTeeFitting3.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewTeeFitting_" data-uid="OpenMEP.Element.MEPCurve.NewTeeFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewTeeFitting_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewTeeFitting(Revit.Elements.Element,Revit.Elements.Element)">
  NewTeeFitting(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L276"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Create a new tee fitting 90 degrees by two mep curve</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? NewTeeFitting(Element MepCurve1, Element MepCurve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>MepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first element mep curve</p>
</dd>
    <dt><code>MepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second element mep curve</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>the element family instance</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewTeeFitting_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewTeeFitting2.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewTransitionFitting_" data-uid="OpenMEP.Element.MEPCurve.NewTransitionFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewTransitionFitting_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewTransitionFitting(Revit.Elements.Element,Revit.Elements.Element)">
  NewTransitionFitting(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L342"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Add a new family instance of an transition fitting into the Autodesk Revit document,
using two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewTransitionFitting(Element mepCurve1, Element mepCurve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>the first mepCurve(Pipe/Duct/CableTray)</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>the second mepCurve(Pipe/Duct/CableTray)</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>new transition</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewTransitionFitting_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewTransitionFitting.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_NewUnionFitting_" data-uid="OpenMEP.Element.MEPCurve.NewUnionFitting*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_NewUnionFitting_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.NewUnionFitting(Revit.Elements.Element,Revit.Elements.Element)">
  NewUnionFitting(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L119"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>create a union fitting from two mep curve</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? NewUnionFitting(Element mepCurve1, Element mepCurve2)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve1</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend first elements.</p>
</dd>
    <dt><code>mepCurve2</code> <span class="xref">Element</span></dt>
    <dd><p>A curve object for duct or pipe blend second elements.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>union fitting</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_NewUnionFitting_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.NewUnionFitting.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_ReferenceLevel_" data-uid="OpenMEP.Element.MEPCurve.ReferenceLevel*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_ReferenceLevel_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.ReferenceLevel(Revit.Elements.Element)">
  ReferenceLevel(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L499"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The reference level of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static Element? ReferenceLevel(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_ReferenceLevel_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.ReferenceLevel.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_MEPCurve_ReferenceLevel_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the reference level of the MEP curve.
If the curve is not in a horizontal plane, this value will be the start point's reference level.</p>
</div>




  <a id="OpenMEP_Element_MEPCurve_Slope_" data-uid="OpenMEP.Element.MEPCurve.Slope*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_Slope_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.MEPCurve.Slope(Revit.Elements.Element,System.Double)">
  Slope(Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L617"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Return the slope of mepCurve</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;Percent&quot;, &quot;Degrees&quot;, &quot;Ratio&quot; })]
[NodeCategory(&quot;Query&quot;)]
public static Dictionary&lt;string, object?&gt; Slope(Element mepCurve, double digit = 0)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd><p>The element mepCurve</p>
</dd>
    <dt><code>digit</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>Number of fractional digits in the return value</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2">Dictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_Slope_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.Slope.png" alt=""></p>






  <a id="OpenMEP_Element_MEPCurve_Width_" data-uid="OpenMEP.Element.MEPCurve.Width*"></a>

  <h3 id="OpenMEP_Element_MEPCurve_Width_Revit_Elements_Element_" data-uid="OpenMEP.Element.MEPCurve.Width(Revit.Elements.Element)">
  Width(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/MEPCurve.cs/#L419"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The width of the MEP curve.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double? Width(Element mepCurve)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>mepCurve</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a>?</dt>
    <dd><p>width of mep curve</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_MEPCurve_Width_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/MEPCurve.Width.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_MEPCurve_Width_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>This property is used to retrieve the width of the MEP curve.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the MEP curve's shape is not rectangular.</p>
</dd>
  </dl>



</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_MEPCurve.md&amp;value=---%0Auid%3A%20OpenMEP.Element.MEPCurve%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>