<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Duct
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Duct
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Duct.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Duct%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.Duct">


  <h1 id="OpenMEP_Element_Duct" data-uid="OpenMEP.Element.Duct" class="text-break">
    Class Duct
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L13"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>A duct in the Autodesk Revit MEP product.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class Duct</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Duct</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>




  <h2 id="OpenMEP_Element_Duct_remarks">Remarks</h2>
  <div class="markdown level0 remarks"><p>The duct is only available in the Autodesk Revit MEP product.</p>
</div>

  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_Duct_ConnectAirTerminalOnDuct_" data-uid="OpenMEP.Element.Duct.ConnectAirTerminalOnDuct*"></a>

  <h3 id="OpenMEP_Element_Duct_ConnectAirTerminalOnDuct_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.ConnectAirTerminalOnDuct(Revit.Elements.Element,Revit.Elements.Element)">
  ConnectAirTerminalOnDuct(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L735"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Connects an air terminal to a duct directly (without the need for a tee or takeoff).</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static bool ConnectAirTerminalOnDuct(Element airTerminal, Element duct)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>airTerminal</code> <span class="xref">Element</span></dt>
    <dd><p>The air terminal element.</p>
</dd>
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>The duct curve element.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>True if connection succeeds, false otherwise.</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Duct_ConnectAirTerminalOnDuct_Revit_Elements_Element_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>The current location of the air terminal will be projected to the duct centerline, and if the point can be successfully projected,
the air terminal will be placed on the most suitable face of the duct.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The familyinstance is not air terminal.
-or-
The element is not duct curve.
-or-
The air terminal already has physical connection.
-or-
The air terminal connector origin doesn't project within the center line of the duct.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_ConvertPlaceholdersToDucts_" data-uid="OpenMEP.Element.Duct.ConvertPlaceholdersToDucts*"></a>

  <h3 id="OpenMEP_Element_Duct_ConvertPlaceholdersToDucts_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.ConvertPlaceholdersToDucts(Revit.Elements.Element)">
  ConvertPlaceholdersToDucts(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L766"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Converts a collection of duct placeholder elements into duct elements.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Element?&gt; ConvertPlaceholdersToDucts(Element ductPlaceholder)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductPlaceholder</code> <span class="xref">Element</span></dt>
    <dd><p>A collection of element of duct placeholder.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Element</span>&gt;</dt>
    <dd><p>A collection of element IDs of ducts and fittings.</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Duct_ConvertPlaceholdersToDucts_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>Once conversion succeeds, the duct placeholder elements are deleted.
The new duct and fitting elements are created and connections are established.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The given element id set is empty.
-or-
The given element IDs (placeholderIds) are not duct placeholders.
-or-
The elements belong to different types of system.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_" data-uid="OpenMEP.Element.Duct.CreateByConnectorAndPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreateByConnectorAndPoint(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.DesignScript.Geometry.Point,System.Double,System.Double)">
  CreateByConnectorAndPoint(Element, Element, Connector, Point, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L199"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct that connects to the connector.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByConnectorAndPoint(Element ductType, Element level, Connector startConnector, Point endPoint, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the new duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the new duct.</p>
</dd>
    <dt><code>startConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector where the new duct starts.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The second point of the new duct.</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByConnectorAndPointSize.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>The new duct will have the same diameter and system type as the specified connector. The creation will also connect the new duct
to the component who owns the specified connector. If necessary, additional fitting(s) are included to make a valid connection.
If the new duct can not be connected to the next component (e.g., mismatched direction, no valid fitting, and etc), the new duct
will still be created at the specified connector position, and an InvalidOperationException is thrown.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The duct type ductTypeId is not valid duct type.
-or-
The ElementId levelId is not a Level.
-or-
The connector's domain is not Domain.â€‹DomainHvac.
-or-
The points of startConnector and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the new duct fails to connect with the connector.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_" data-uid="OpenMEP.Element.Duct.CreateByConnectorAndPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Duct.CreateByConnectorAndPoint(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.DesignScript.Geometry.Point)">
  CreateByConnectorAndPoint(Element, Element, Connector, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L149"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct that connects to the connector.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByConnectorAndPoint(Element ductType, Element level, Connector startConnector, Point endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the new duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the new duct.</p>
</dd>
    <dt><code>startConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector where the new duct starts.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The second point of the new duct.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByConnectorAndPoint.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Duct_CreateByConnectorAndPoint_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_DesignScript_Geometry_Point__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>The new duct will have the same diameter and system type as the specified connector. The creation will also connect the new duct
to the component who owns the specified connector. If necessary, additional fitting(s) are included to make a valid connection.
If the new duct can not be connected to the next component (e.g., mismatched direction, no valid fitting, and etc), the new duct
will still be created at the specified connector position, and an InvalidOperationException is thrown.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The duct type ductTypeId is not valid duct type.
-or-
The ElementId levelId is not a Level.
-or-
The connector's domain is not Domain.â€‹DomainHvac.
-or-
The points of startConnector and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the new duct fails to connect with the connector.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByLine_" data-uid="OpenMEP.Element.Duct.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreateByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,System.Double,System.Double)">
  CreateByLine(Element, Element, Element, Line, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L351"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct from Line.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element systemType, Element ductType, Element level, Line line, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the duct.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line to draw new duct</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByLine.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The duct type ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByLine_" data-uid="OpenMEP.Element.Duct.CreateByLine*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_" data-uid="OpenMEP.Element.Duct.CreateByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line)">
  CreateByLine(Element, Element, Element, Line)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L315"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct from Line.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByLine(Element systemType, Element ductType, Element level, Line line)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the duct.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line to draw new duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByLine.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The duct type ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByTwoConnector_" data-uid="OpenMEP.Element.Duct.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreateByTwoConnector(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,System.Double,System.Double)">
  CreateByTwoConnector(Element, Element, Connector, Connector, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L103"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct that connects to two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element ductType, Element level, Connector startConnector, Connector endConnector, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the new duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level Element for the new duct.</p>
</dd>
    <dt><code>startConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector where the new duct starts.</p>
</dd>
    <dt><code>endConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second point of the new duct.</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByTwoConnectorSize.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_System_Double_System_Double__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>The new duct will have the same diameter and system type as the start connector. The creation will also connect the new duct
to two component who owns the specified connectors. If necessary, additional fitting(s) are included to make a valid connection.
If the new duct can not be connected to the next component (e.g., mismatched direction, no valid fitting, and etc), the new duct
will still be created at the specified connector position, and an InvalidOperationException is thrown.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The duct type ductTypeId is not valid duct type.
-or-
The ElementId levelId is not a Level.
-or-
The connector's domain is not Domain.â€‹DomainHvac.
-or-
The points of startConnector and endConnector are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the new duct fails to connect with the connector.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByTwoConnector_" data-uid="OpenMEP.Element.Duct.CreateByTwoConnector*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Duct.CreateByTwoConnector(Revit.Elements.Element,Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  CreateByTwoConnector(Element, Element, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L53"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct that connects to two connectors.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoConnector(Element ductType, Element level, Connector startConnector, Connector endConnector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the new duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level Element for the new duct.</p>
</dd>
    <dt><code>startConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The first connector where the new duct starts.</p>
</dd>
    <dt><code>endConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The second point of the new duct.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByTwoConnector.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoConnector_Revit_Elements_Element_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>The new duct will have the same diameter and system type as the start connector. The creation will also connect the new duct
to two component who owns the specified connectors. If necessary, additional fitting(s) are included to make a valid connection.
If the new duct can not be connected to the next component (e.g., mismatched direction, no valid fitting, and etc), the new duct
will still be created at the specified connector position, and an InvalidOperationException is thrown.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The duct type ductTypeId is not valid duct type.
-or-
The ElementId levelId is not a Level.
-or-
The connector's domain is not Domain.â€‹DomainHvac.
-or-
The points of startConnector and endConnector are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Thrown when the new duct fails to connect with the connector.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByTwoPoint_" data-uid="OpenMEP.Element.Duct.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreateByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,System.Double,System.Double)">
  CreateByTwoPoint(Element, Element, Element, Point, Point, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L280"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct from two points.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element systemType, Element ductType, Element level, Point startPoint, Point endPoint, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the duct.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the duct.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the duct.</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByTwoPointSize.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The duct type ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreateByTwoPoint_" data-uid="OpenMEP.Element.Duct.CreateByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Duct.CreateByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
  CreateByTwoPoint(Element, Element, Element, Point, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L238"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new duct from two points.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreateByTwoPoint(Element systemType, Element ductType, Element level, Point startPoint, Point endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The level for the duct.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The start point of the duct.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The end point of the duct.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreateByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreateByTwoPoint.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The duct type ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreatePlaceholderByLine_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByLine*"></a>

  <h3 id="OpenMEP_Element_Duct_CreatePlaceholderByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line,System.Double,System.Double)">
  CreatePlaceholderByLine(Element, Element, Element, Line, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L505"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new placeholder duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreatePlaceholderByLine(Element systemType, Element ductType, Element level, Line line, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element level for the duct.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line to draw duct from start point to end point</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created placeholder duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreatePlaceholderByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreatePlaceholderByLineSize.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreatePlaceholderByLine_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByLine*"></a>

  <h3 id="OpenMEP_Element_Duct_CreatePlaceholderByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByLine(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Line)">
  CreatePlaceholderByLine(Element, Element, Element, Line)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L427"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new placeholder duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreatePlaceholderByLine(Element systemType, Element ductType, Element level, Line line)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element level for the duct.</p>
</dd>
    <dt><code>line</code> <span class="xref">Line</span></dt>
    <dd><p>the line to draw duct from start point to end point</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created placeholder duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreatePlaceholderByLine_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Line__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreatePlaceholderByLine.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,System.Double,System.Double)">
  CreatePlaceholderByTwoPoint(Element, Element, Element, Point, Point, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L463"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new placeholder duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreatePlaceholderByTwoPoint(Element systemType, Element ductType, Element level, Point startPoint, Point endPoint, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element level for the duct.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The first point of the placeholder line.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The second point of the placeholder line.</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created placeholder duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreatePlaceholderByTwoPointSize.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByTwoPoint*"></a>

  <h3 id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Duct.CreatePlaceholderByTwoPoint(Revit.Elements.Element,Revit.Elements.Element,Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
  CreatePlaceholderByTwoPoint(Element, Element, Element, Point, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L388"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Creates a new placeholder duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Create&quot;)]
public static Element? CreatePlaceholderByTwoPoint(Element systemType, Element ductType, Element level, Point startPoint, Point endPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the HVAC system type.</p>
</dd>
    <dt><code>ductType</code> <span class="xref">Element</span></dt>
    <dd><p>The element of the duct type.</p>
</dd>
    <dt><code>level</code> <span class="xref">Element</span></dt>
    <dd><p>The element level for the duct.</p>
</dd>
    <dt><code>startPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The first point of the placeholder line.</p>
</dd>
    <dt><code>endPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The second point of the placeholder line.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>The created placeholder duct.</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_CreatePlaceholderByTwoPoint_Revit_Elements_Element_Revit_Elements_Element_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_Autodesk_DesignScript_Geometry_Point__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.CreatePlaceholderByTwoPoint.png" alt=""></p>



  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemType is not valid HVAC system type.
-or-
The ductType is not valid duct type.
-or-
The Element level is not a Level.
-or-
The points of startPoint and endPoint are too close: for MEPCurve, the minimum length is 1/10 inch.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_GetDiameter_" data-uid="OpenMEP.Element.Duct.GetDiameter*"></a>

  <h3 id="OpenMEP_Element_Duct_GetDiameter_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.GetDiameter(Revit.Elements.Element)">
  GetDiameter(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L582"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>return diameter of duct</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[MultiReturn(new string[] { &quot;width&quot;, &quot;height&quot;, &quot;diameter&quot; })]
[NodeCategory(&quot;Query&quot;)]
public static Dictionary&lt;string, object?&gt; GetDiameter(Element duct)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>the duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2">Dictionary</a>&lt;<a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a>, <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a>&gt;</dt>
    <dd></dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_GetDiameter_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.GetDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Duct_IsDuctTypeId_" data-uid="OpenMEP.Element.Duct.IsDuctTypeId*"></a>

  <h3 id="OpenMEP_Element_Duct_IsDuctTypeId_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.IsDuctTypeId(Revit.Elements.Element)">
  IsDuctTypeId(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L705"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Check if the element of duct is a valid duct type</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static bool IsDuctTypeId(Element systemType)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>the system type of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>true if is duct type id</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_IsDuctTypeId_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.IsDuctTypeId.png" alt=""></p>






  <a id="OpenMEP_Element_Duct_IsHvacSystemTypeId_" data-uid="OpenMEP.Element.Duct.IsHvacSystemTypeId*"></a>

  <h3 id="OpenMEP_Element_Duct_IsHvacSystemTypeId_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.IsHvacSystemTypeId(Revit.Elements.Element)">
  IsHvacSystemTypeId(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L688"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Check if the element of duct is a valid system type</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static bool IsHvacSystemTypeId(Element systemType)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>the element of system type</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>true if is HvacSystemTypeId</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_IsHvacSystemTypeId_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.IsHvacSystemTypeId.png" alt=""></p>






  <a id="OpenMEP_Element_Duct_SetDiameter_" data-uid="OpenMEP.Element.Duct.SetDiameter*"></a>

  <h3 id="OpenMEP_Element_Duct_SetDiameter_Revit_Elements_Element_System_Double_System_Double_" data-uid="OpenMEP.Element.Duct.SetDiameter(Revit.Elements.Element,System.Double,System.Double)">
  SetDiameter(Element, double, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L526"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set new diameter for rectangular duct</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? SetDiameter(Element duct, double width, double height)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>the duct to set diameter</p>
</dd>
    <dt><code>width</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value width of duct</p>
</dd>
    <dt><code>height</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value height of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>duct with new parameter diameter</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_SetDiameter_Revit_Elements_Element_System_Double_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.SetDiameterSize.png" alt=""></p>






  <a id="OpenMEP_Element_Duct_SetDiameter_" data-uid="OpenMEP.Element.Duct.SetDiameter*"></a>

  <h3 id="OpenMEP_Element_Duct_SetDiameter_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Duct.SetDiameter(Revit.Elements.Element,System.Double)">
  SetDiameter(Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L556"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Set new diameter for round duct</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element? SetDiameter(Element duct, double diameter)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>the duct to set diameter</p>
</dd>
    <dt><code>diameter</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>new value diameter of duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>duct with new parameter diameter</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_SetDiameter_Revit_Elements_Element_System_Double__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.SetDiameter.png" alt=""></p>






  <a id="OpenMEP_Element_Duct_SetSystemType_" data-uid="OpenMEP.Element.Duct.SetSystemType*"></a>

  <h3 id="OpenMEP_Element_Duct_SetSystemType_Revit_Elements_Element_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.SetSystemType(Revit.Elements.Element,Revit.Elements.Element)">
  SetSystemType(Element, Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L650"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Updates the associated system type for the duct.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Action&quot;)]
public static Element SetSystemType(Element duct, Element systemType)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the duct</p>
</dd>
    <dt><code>systemType</code> <span class="xref">Element</span></dt>
    <dd><p>The Element of the hvac system type.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>duct changed systemType</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_SetSystemType_Revit_Elements_Element_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.SetSystemType.png" alt=""></p>


  <h4 class="section" id="OpenMEP_Element_Duct_SetSystemType_Revit_Elements_Element_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the duct previously did not have a system associated to it, this will create a new system.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The systemTypeId is not valid HVAC system type.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Duct_Shape_" data-uid="OpenMEP.Element.Duct.Shape*"></a>

  <h3 id="OpenMEP_Element_Duct_Shape_Revit_Elements_Element_" data-uid="OpenMEP.Element.Duct.Shape(Revit.Elements.Element)">
  Shape(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Duct.cs/#L671"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Get Shape Type of duct</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static dynamic Shape(Element duct)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>duct</code> <span class="xref">Element</span></dt>
    <dd><p>the duct</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">dynamic</span></dt>
    <dd><p>shape type of duct</p>
</dd>
  </dl>






  <h4 class="section" id="OpenMEP_Element_Duct_Shape_Revit_Elements_Element__examples">Examples</h4>
  <p><img src="../OpenMEPPage/element/dyn/pic/Duct.Shape.png" alt=""></p>






</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Duct.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Duct%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>