<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Class Wire
 | Open MEP </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Class Wire
 | Open MEP ">
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../styles/docfx.min.css">
      <link rel="stylesheet" href="../styles/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      
      <meta name="docfx:docurl" content="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Wire.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Wire%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A">
  </head>

  <body data-layout="" data-yaml-mime="ManagedReference">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/logo.png" alt="">
            
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbar">
            <form class="d-flex ms-auto" role="search" id="search">
              <i class="bi bi-search"></i>
              <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="OpenMEP.Element.Wire">


  <h1 id="OpenMEP_Element_Wire" data-uid="OpenMEP.Element.Wire" class="text-break">
    Class Wire
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L10"><i class="bi bi-code-slash"></i></a>
  </h1>

  <div class="facts text-secondary">
    <dl><dt>Namespace</dt><dd><span class="xref">OpenMEP</span>.<a class="xref" href="OpenMEP.Element.html">Element</a></dd></dl>
    <dl><dt>Assembly</dt><dd>OpenMEP.dll</dd></dl>
  </div>

  <div class="markdown summary"><p>Electrical wire element.</p>
</div>
  <div class="markdown conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public class Wire</code></pre>
  </div>




  <dl class="typelist inheritance">
    <dt>Inheritance</dt>
    <dd>
      <div><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object">object</a></div>
      <div><span class="xref">Wire</span></div>
    </dd>
  </dl>



  <dl class="typelist derived">
    <dt>Inherited Members</dt>
    <dd>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.tostring#system-object-tostring">object.ToString()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)">object.Equals(object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)">object.Equals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.referenceequals#system-object-referenceequals(system-object-system-object)">object.ReferenceEquals(object, object)</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gethashcode#system-object-gethashcode">object.GetHashCode()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.gettype#system-object-gettype">object.GetType()</a>
    </div>
    <div>
      <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone#system-object-memberwiseclone">object.MemberwiseClone()</a>
    </div>
  </dd></dl>





  <h2 class="section" id="methods">Methods
</h2>

  <a id="OpenMEP_Element_Wire_AppendVertex_" data-uid="OpenMEP.Element.Wire.AppendVertex*"></a>

  <h3 id="OpenMEP_Element_Wire_AppendVertex_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Wire.AppendVertex(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
  AppendVertex(Element, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L33"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Appends one vertex to the end of the wire.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Element AppendVertex(Element wire, Point vertexPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>vertexPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The vertex to be appended.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Element</span></dt>
    <dd><p>wire</p>
</dd>
  </dl>








  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The vertex point cannot be added to the wire because there is already a vertex at this position on the view plane (within tolerance).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The end point is already connected to an element, so a new endpoint vertex cannot be appended.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_AreVertexPointsValid_" data-uid="OpenMEP.Element.Wire.AreVertexPointsValid*"></a>

  <h3 id="OpenMEP_Element_Wire_AreVertexPointsValid_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Wire.AreVertexPointsValid(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point},Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  AreVertexPointsValid(List&lt;Point&gt;, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L57"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Checks if the given vertex points are valid for the wire.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static bool AreVertexPointsValid(List&lt;Point&gt; vertexPoints, Connector startConnector, Connector endConnector)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>vertexPoints</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1">List</a>&lt;<span class="xref">Point</span>&gt;</dt>
    <dd><p>The vertex points.</p>
</dd>
    <dt><code>startConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The start connector of the wire.</p>
</dd>
    <dt><code>endConnector</code> <span class="xref">Connector</span></dt>
    <dd><p>The end connector of the wire.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>True if the given vertex points are valid, false otherwise.</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Wire_AreVertexPointsValid_System_Collections_Generic_List_Autodesk_DesignScript_Geometry_Point__Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>X and Y values are compared of the vertices.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_ConnectTo_" data-uid="OpenMEP.Element.Wire.ConnectTo*"></a>

  <h3 id="OpenMEP_Element_Wire_ConnectTo_Revit_Elements_Element_Autodesk_Revit_DB_Connector_Autodesk_Revit_DB_Connector_" data-uid="OpenMEP.Element.Wire.ConnectTo(Revit.Elements.Element,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
  ConnectTo(Element, Connector, Connector)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L86"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Connects the wire to other elements.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static void ConnectTo(Element wire, Connector startConnectorTo, Connector endConnectorTo)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>startConnectorTo</code> <span class="xref">Connector</span></dt>
    <dd><p>The connector that the start connector of the wire connects to.</p>
</dd>
    <dt><code>endConnectorTo</code> <span class="xref">Connector</span></dt>
    <dd><p>The connector that the end connector of the wire connects to.</p>
</dd>
  </dl>









  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>startConnectorTo cannot be connected to a wire, as it is not an electrical connector.
-or-
endConnectorTo cannot be connected to a wire, as it is not an electrical connector.
-or-
startConnectorTo or/and endConnectorTo cannot be connected to a wire, as wire can't connect both connectors to same wire or same connector.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Cannot connect the wire to the start connector or the end connector.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_GetMEPSystems_" data-uid="OpenMEP.Element.Wire.GetMEPSystems*"></a>

  <h3 id="OpenMEP_Element_Wire_GetMEPSystems_Revit_Elements_Element_" data-uid="OpenMEP.Element.Wire.GetMEPSystems(Revit.Elements.Element)">
  GetMEPSystems(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L105"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Gets the systems to which the wire belongs.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static IEnumerable&lt;Element?&gt; GetMEPSystems(Element wire)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.collections.generic.ienumerable-1">IEnumerable</a>&lt;<span class="xref">Element</span>&gt;</dt>
    <dd><p>The systems to which the wire belongs.</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Wire_GetMEPSystems_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>One wire might belong to more than one circuit.</p>
</div>




  <a id="OpenMEP_Element_Wire_GetVertex_" data-uid="OpenMEP.Element.Wire.GetVertex*"></a>

  <h3 id="OpenMEP_Element_Wire_GetVertex_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Wire.GetVertex(Revit.Elements.Element,System.Double)">
  GetVertex(Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L139"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Gets the position of an existing vertex.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">public static Point? GetVertex(Element wire, double index)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>index</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>The index of the existing vertex. Should be between 0 and <span class="xref">Autodesk.Revit.DB.Electrical.Wire.NumberOfVertices</span>.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point</span></dt>
    <dd><p>The position of the vertex.
It is the offset point for the start and end vertex, not the connector point.
If the wire connects to one device, it may have offset; otherwise, the start and end vertex is same as the connector point.</p>
</dd>
  </dl>








  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The index should be between 0 and the number of vertices of the wire.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_GroundConductorNumber_" data-uid="OpenMEP.Element.Wire.GroundConductorNumber*"></a>

  <h3 id="OpenMEP_Element_Wire_GroundConductorNumber_Revit_Elements_Element_" data-uid="OpenMEP.Element.Wire.GroundConductorNumber(Revit.Elements.Element)">
  GroundConductorNumber(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L272"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The ground conductor number. Its default value is zero after created.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double GroundConductorNumber(Element wire)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>ground conductor number</p>
</dd>
  </dl>











  <a id="OpenMEP_Element_Wire_HotConductorNum_" data-uid="OpenMEP.Element.Wire.HotConductorNum*"></a>

  <h3 id="OpenMEP_Element_Wire_HotConductorNum_Revit_Elements_Element_" data-uid="OpenMEP.Element.Wire.HotConductorNum(Revit.Elements.Element)">
  HotConductorNum(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L283"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The hot conductor number. Its default value is zero after created.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double HotConductorNum(Element wire)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>hot conduct number</p>
</dd>
  </dl>











  <a id="OpenMEP_Element_Wire_InsertVertex_" data-uid="OpenMEP.Element.Wire.InsertVertex*"></a>

  <h3 id="OpenMEP_Element_Wire_InsertVertex_Revit_Elements_Element_System_Double_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Wire.InsertVertex(Revit.Elements.Element,System.Double,Autodesk.DesignScript.Geometry.Point)">
  InsertVertex(Element, double, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L171"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Inserts a new vertex before the specified index.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Actions&quot;)]
public static Point? InsertVertex(Element wire, double index, Point vertexPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>index</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>The index of the vertex to come after this new vertex. Should be between 0 and <span class="xref">Autodesk.Revit.DB.Electrical.Wire.NumberOfVertices</span>.</p>
</dd>
    <dt><code>vertexPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The point of the new vertex.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><span class="xref">Point</span></dt>
    <dd></dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Wire_InsertVertex_Revit_Elements_Element_System_Double_Autodesk_DesignScript_Geometry_Point__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>To add a new vertex to the end of the wire, use <span class="xref">Autodesk.Revit.DB.Electrical.Wire.AppendVertex(Autodesk.Revit.DB.XYZ)</span>.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The index should be between 0 and the number of vertices of the wire.
-or-
The vertex point cannot be added to the wire because there is already a vertex at this position on the view plane (within tolerance).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Can't insert the vertex before the start vertex if the start point connects to one element.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_IsVertexPointValid_" data-uid="OpenMEP.Element.Wire.IsVertexPointValid*"></a>

  <h3 id="OpenMEP_Element_Wire_IsVertexPointValid_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Wire.IsVertexPointValid(Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point)">
  IsVertexPointValid(Element, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L195"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Checks if the given vertex point can be added to this wire.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static bool IsVertexPointValid(Element wire, Point vertexPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>vertexPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The vertex point.</p>
</dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.boolean">bool</a></dt>
    <dd><p>True if the vertex point can be added, false if the point cannot be added because there is already a vertex at this position on the view plane (within tolerance).</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Wire_IsVertexPointValid_Revit_Elements_Element_Autodesk_DesignScript_Geometry_Point__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>Vertices are projected to the view plane for comparison.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_NeutralConductorNum_" data-uid="OpenMEP.Element.Wire.NeutralConductorNum*"></a>

  <h3 id="OpenMEP_Element_Wire_NeutralConductorNum_Revit_Elements_Element_" data-uid="OpenMEP.Element.Wire.NeutralConductorNum(Revit.Elements.Element)">
  NeutralConductorNum(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L294"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The neutral conductor number. Its default value is zero after created.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static double NeutralConductorNum(Element wire)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>neutral conductor number</p>
</dd>
  </dl>











  <a id="OpenMEP_Element_Wire_RemoveVertex_" data-uid="OpenMEP.Element.Wire.RemoveVertex*"></a>

  <h3 id="OpenMEP_Element_Wire_RemoveVertex_Revit_Elements_Element_System_Double_" data-uid="OpenMEP.Element.Wire.RemoveVertex(Revit.Elements.Element,System.Double)">
  RemoveVertex(Element, double)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L222"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Removes the vertex corresponding to the specified index.
Can not remove the start or end vertex if it already connects to other element.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Actions&quot;)]
public static void RemoveVertex(Element wire, double index)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>index</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>The index which should be in [0, NumberOfVertices).</p>
</dd>
  </dl>









  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The index should be between 0 and the number of vertices of the wire.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>The wire has only 2 vertices, so one cannot be removed.
-or-
Can't remove the vertex when the vertex is start or end point and the wire connects to one element.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_SetVertex_" data-uid="OpenMEP.Element.Wire.SetVertex*"></a>

  <h3 id="OpenMEP_Element_Wire_SetVertex_Revit_Elements_Element_System_Double_Autodesk_DesignScript_Geometry_Point_" data-uid="OpenMEP.Element.Wire.SetVertex(Revit.Elements.Element,System.Double,Autodesk.DesignScript.Geometry.Point)">
  SetVertex(Element, double, Point)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L258"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>Sets the position of a given vertex.
If the vertex is start or end point, and the wire connects to electrical device, the wire end offset will be set according to the given vertex.
If the vertex is start or end point, and the wire connects to other wire, user can't set the vertex and exception will be thrown.
If the vertex is start or end point, and the wire connects to nothing, the vertex will be set as the given vertex.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Actions&quot;)]
public static void SetVertex(Element wire, double index, Point vertexPoint)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd><p>the wire</p>
</dd>
    <dt><code>index</code> <a class="xref" href="https://learn.microsoft.com/dotnet/api/system.double">double</a></dt>
    <dd><p>The index of the existing vertex. Should be between 0 and <span class="xref">Autodesk.Revit.DB.Electrical.Wire.NumberOfVertices</span>.</p>
</dd>
    <dt><code>vertexPoint</code> <span class="xref">Point</span></dt>
    <dd><p>The new position for the vertex.</p>
</dd>
  </dl>









  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentException</span></dt>
    <dd><p>The index should be between 0 and the number of vertices of the wire.
-or-
The vertex point cannot be added to the wire because there is already a vertex at this position on the view plane (within tolerance).</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentNullException</span></dt>
    <dd><p>A non-optional argument was null</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.DisabledDisciplineException</span></dt>
    <dd><p>None of the following disciplines is enabled: Mechanical Electrical Piping.</p>
</dd>
    <dt><span class="xref">Autodesk.Revit.Exceptions.InvalidOperationException</span></dt>
    <dd><p>Can't set the vertex when the vertex is start or end point and the wire connects to other wire.</p>
</dd>
  </dl>



  <a id="OpenMEP_Element_Wire_WiringType_" data-uid="OpenMEP.Element.Wire.WiringType*"></a>

  <h3 id="OpenMEP_Element_Wire_WiringType_Revit_Elements_Element_" data-uid="OpenMEP.Element.Wire.WiringType(Revit.Elements.Element)">
  WiringType(Element)
  <a class="header-action link-secondary" title="View source" href="https://github.com/chuongmep/OpenMEP/blob/docs/OpenMEP/Element/Wire.cs/#L310"><i class="bi bi-code-slash"></i></a>
  </h3>

  <div class="markdown level1 summary"><p>The wiring type(arc or chamfer) for the wire.</p>
</div>
  <div class="markdown level1 conceptual"></div>

  <div class="codewrapper">
    <pre><code class="lang-csharp hljs">[NodeCategory(&quot;Query&quot;)]
public static string? WiringType(Element wire)</code></pre>
  </div>

  <h4 class="section">Parameters</h4>
  <dl class="parameters">
    <dt><code>wire</code> <span class="xref">Element</span></dt>
    <dd></dd>
  </dl>

  <h4 class="section">Returns</h4>
  <dl class="parameters">
    <dt><a class="xref" href="https://learn.microsoft.com/dotnet/api/system.string">string</a></dt>
    <dd><p>wiring type of wire</p>
</dd>
  </dl>







  <h4 class="section" id="OpenMEP_Element_Wire_WiringType_Revit_Elements_Element__remarks">Remarks</h4>
  <div class="markdown level1 remarks"><p>If the WiringType is arc, the shape of the wire depends on the number of points - it may be linear, a circular arc, or a spline.</p>
</div>

  <h4 class="section">Exceptions</h4>
  <dl class="parameters">
    <dt><span class="xref">Autodesk.Revit.Exceptions.ArgumentOutOfRangeException</span></dt>
    <dd><p>When setting this property: A value passed for an enumeration argument is not a member of that enumeration</p>
</dd>
  </dl>



</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/chuongmep/openmep/new/dev/apiSpec/new?filename=OpenMEP_Element_Wire.md&amp;value=---%0Auid%3A%20OpenMEP.Element.Wire%0Asummary%3A%20&#39;*You%20can%20override%20summary%20for%20the%20API%20here%20using%20*MARKDOWN*%20syntax&#39;%0A---%0A%0A*Please%20type%20below%20more%20information%20about%20this%20API%3A*%0A%0A" class="edit-link">Edit this page</a>
        </div>
      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>


    <footer class="border-top">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Made with <a href="https://dotnet.github.io/docfx">docfx</a></span>
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="../styles/docfx.min.js"></script>
    <script type="text/javascript" src="../styles/main.js"></script>
  </body>
</html>